# Generated by Django 6.0.1 on 2026-02-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"permissions": [("student", "Student")]},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"permissions": [("teacher", "Teacher")]},
        ),
    ]
