# Generated by Django 6.0.1 on 2026-02-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_student_options_alter_teacher_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="associated_quizzes",
            field=models.ManyToManyField(to="quiz.quizzes"),
        ),
    ]
