# Generated by Django 6.0.1 on 2026-02-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quizzes_question_associated_quizzes"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizzes",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.teacher",
            ),
            preserve_default=False,
        ),
    ]
