# Generated by Django 6.0.1 on 2026-02-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_quizzes_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizzes",
            name="author",
        ),
    ]
